[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/invite/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  VITE_SUPABASE_URL = "https://igsywszdbsxegmsqgfif.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlnc3l3c3pkYnN4ZWdtc3FnZmlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk3MTQyNjgsImV4cCI6MjA1NTI5MDI2OH0.uqJTwoOC6nx2H766lMAbRuhySx6pGGUqWJBJZcKY1oQ"